export const salon = {
  name: 'BlackSilva',
  email: 'blacksilvahd@gmail.com',
  address: 'Badstuestraede 16, 1053 Kobenhavn',
  mapsUrl:
    'https://www.google.com/maps/search/?api=1&query=Badstuestr%C3%A6de+16%2C+1053+K%C3%B8benhavn',
  hours: 'Wed 14-20 / Thu-Sun 11-17',
};

export const stylists = [
  {
    id: 'eduard',
    name: 'Eduard',
    role: 'Men grooming specialist',
    initial: 'E',
    focus: "Since 2018, I've helped over 800 clients walk out looking exactly how they want to be seen.",
    specialties: ['Men haircuts', 'Beard', 'Grooming'],
  },
  {
    id: 'elena',
    name: 'Elena',
    role: 'Women hair specialist',
    initial: 'E',
    focus: "Since 2018, I've helped over 800 clients walk out looking exactly how they want to be seen.",
    specialties: ['Women haircuts', 'Styling', 'Unisex'],
  },
  {
    id: 'chair',
    name: 'Chair 01',
    role: 'Rentable salon station',
    initial: 'C',
    focus: 'A ready salon station for independent barbers or stylists, with direct booking access.',
    specialties: ['Chair rental', 'Studio'],
  },
];

export const services = [
  {
    id: 'module-2',
    name: 'MODULE 2',
    category: 'Masterclass',
    duration: 5,
    price: 1000,
    priceLabel: '1.000 kr',
    staffIds: ['eduard'],
    preferredStylistId: 'eduard',
    description: 'Train under a master and move closer to elite barber confidence.',
  },
  {
    id: 'module-3',
    name: 'MODULE 3',
    category: 'Masterclass',
    duration: 5,
    price: 1000,
    priceLabel: '1.000 kr',
    staffIds: ['eduard'],
    preferredStylistId: 'eduard',
    description: 'Build the control and confidence needed for advanced skinfade work.',
  },
  {
    id: 'module-4',
    name: 'MODULE 4',
    category: 'Masterclass',
    duration: 5,
    price: 1000,
    priceLabel: '1.000 kr',
    staffIds: ['eduard'],
    preferredStylistId: 'eduard',
    description: 'Finish the training path ready to cut, advise, and communicate like a pro.',
  },
  {
    id: 'ladys-haircut-long-hair',
    name: "Lady's Haircut Long Hair",
    category: 'Haircut With Elena',
    duration: 90,
    price: 650,
    priceLabel: 'from 650 kr',
    staffIds: ['elena'],
    preferredStylistId: 'elena',
    description: 'Walk out with long hair that feels healthy, shaped, and fully finished.',
    popular: true,
  },
  {
    id: 'ladys-haircut-medium-short',
    name: "Lady's Haircut - Medium & Short Hair (Max 20 CM)",
    category: 'Haircut With Elena',
    duration: 75,
    price: 500,
    priceLabel: 'from 500 kr',
    staffIds: ['elena'],
    preferredStylistId: 'elena',
    description: 'Refresh your shape so your hair feels lighter, cleaner, and easier to wear.',
  },
  {
    id: 'elegant-scissors-haircut-only',
    name: 'Elegant Scissors Haircut (Scissors Only)',
    category: 'Haircut With Eduard',
    duration: 60,
    price: 470,
    priceLabel: 'from 470 kr',
    staffIds: ['eduard'],
    preferredStylistId: 'eduard',
    description: 'Leave with a precise, timeless silhouette that looks calm and expensive.',
    popular: true,
  },
  {
    id: 'elegant-scissors-haircut-men-elena',
    name: 'Elegant Scissors Haircut (For Men)',
    category: 'Haircut With Eduard',
    duration: 60,
    price: 400,
    priceLabel: 'from 400 kr',
    staffIds: ['eduard'],
    preferredStylistId: 'eduard',
    description: 'Step out with a polished shape that feels tailored to your face.',
  },
  {
    id: 'classic-skin-fade-scissors-top',
    name: 'Classic or Skin Fade Haircut + Scissors on the top',
    category: 'Featured',
    duration: 50,
    price: 375,
    priceLabel: 'from 375 kr',
    staffIds: ['eduard'],
    preferredStylistId: 'eduard',
    description: 'Leave with a clean fade and a sharper shape from every angle.',
    popular: true,
  },
  {
    id: 'undercut-10-12-scissors-top',
    name: 'Undercut ( 10mm or 12mm + Scissors top )',
    category: 'Haircut With Eduard',
    duration: 30,
    price: 310,
    priceLabel: 'from 310 kr',
    staffIds: ['eduard'],
    preferredStylistId: 'eduard',
    description: 'Get a sharp undercut that keeps the top controlled and the sides clean.',
  },
  {
    id: 'classic-fade-no-skin-fade',
    name: 'Classic Fade Cut ( From 2mm ) *No Skin Fade',
    category: 'Featured',
    duration: 60,
    price: 300,
    priceLabel: 'from 300 kr',
    staffIds: ['eduard'],
    preferredStylistId: 'eduard',
    description: 'Keep it neat, blended, and modern without going down to skin.',
  },
  {
    id: 'undercut-from-12-scissors-top',
    name: 'Undercut (From 12mm) + Scissors Top',
    category: 'Haircut With Eduard',
    duration: 40,
    price: 250,
    priceLabel: 'from 250 kr',
    staffIds: ['eduard'],
    preferredStylistId: 'eduard',
    description: 'Walk out clean, structured, and easy to style the next morning.',
  },
  {
    id: 'gentleman-beard-trimming',
    name: 'Gentleman Beard Trimming 💈',
    category: 'Featured',
    duration: 20,
    price: 125,
    priceLabel: 'from 125 kr',
    staffIds: ['eduard'],
    preferredStylistId: 'eduard',
    description: 'Frame your face with a beard that looks deliberate, clean, and balanced.',
  },
  {
    id: 'hair-wash-gentlemans',
    name: 'Hair wash Gentlemans',
    category: 'Featured',
    duration: 10,
    price: 65,
    priceLabel: 'from 65 kr',
    staffIds: ['eduard'],
    preferredStylistId: 'eduard',
    description: 'Start fresh so the finish feels cleaner, softer, and more intentional.',
  },
  {
    id: 'booking-protection',
    name: 'Booking Protection',
    category: 'Haircut With Eduard',
    duration: 5,
    price: 59,
    priceLabel: '59 kr',
    staffIds: ['eduard', 'elena'],
    description: 'Book with peace of mind if your plans change.',
  },
  {
    id: 'eyebrows',
    name: 'Eyebrows',
    category: 'Haircut With Eduard',
    duration: 5,
    price: 50,
    priceLabel: '50 kr',
    staffIds: ['eduard'],
    preferredStylistId: 'eduard',
    description: 'Clean up the details so your face looks sharper in seconds.',
  },
  {
    id: 'espresso-double-espresso',
    name: 'Espresso or Double Espresso☕',
    category: 'Drinks List',
    duration: 5,
    price: 10,
    priceLabel: '10 kr',
    staffIds: ['eduard', 'elena'],
    description: 'Add a small coffee ritual to the appointment.',
  },
  {
    id: 'coca-cola',
    name: 'Coca-Cola',
    category: 'Drinks List',
    duration: 5,
    price: 10,
    priceLabel: '10 kr',
    staffIds: ['eduard', 'elena'],
    description: 'Keep the visit relaxed with a cold drink ready for you.',
  },
  {
    id: 'faxe-kondi',
    name: 'Faxe Kondi',
    category: 'Drinks List',
    duration: 5,
    price: 10,
    priceLabel: '10 kr',
    staffIds: ['eduard', 'elena'],
    description: 'Add a cold drink while you wait or after the cut.',
  },
  {
    id: 'gentleman-regular',
    name: 'Gentleman Regular',
    category: 'Membership Services',
    duration: 60,
    price: 0,
    priceLabel: 'free',
    staffIds: ['eduard'],
    preferredStylistId: 'eduard',
    description: 'Use your membership and keep your regular cut rhythm in place.',
  },
  {
    id: 'module-1',
    name: 'MODULE 1',
    category: 'Masterclass',
    duration: 5,
    price: 0,
    priceLabel: 'free',
    staffIds: ['eduard'],
    preferredStylistId: 'eduard',
    description: 'Begin the masterclass path and bring your ticket with confidence.',
  },
  {
    id: 'chair-rental-halfday',
    name: 'Chair Rental / Half Day',
    category: 'Business',
    duration: 240,
    price: 900,
    staffIds: ['chair'],
    description: 'Rent the BlackSilva chair for half a day, with admin confirmation.',
  },
  {
    id: 'chair-rental-day',
    name: 'Chair Rental / Full Day',
    category: 'Business',
    duration: 360,
    price: 1500,
    staffIds: ['chair'],
    description: 'Book a full salon station for one workday.',
  },
];

export const products = [
  { id: 'none', name: 'No product', price: 0, stock: 0, category: 'None' },
  { id: 'stylist-pick', name: 'Stylist pick', price: 180, stock: 12, category: 'Salon Pick' },
  { id: 'texture-spray', name: 'Texture Salt Spray', price: 195, stock: 18, category: 'Styling' },
  { id: 'matte-clay', name: 'Matte Clay', price: 210, stock: 9, category: 'Styling' },
  { id: 'repair-mask', name: 'Repair Mask No.7', price: 320, stock: 6, category: 'Care' },
];

export const openingHours = {
  0: { label: 'Sunday', start: '11:00', end: '17:00' },
  1: null,
  2: null,
  3: { label: 'Wednesday', start: '14:00', end: '20:00' },
  4: { label: 'Thursday', start: '11:00', end: '17:00' },
  5: { label: 'Friday', start: '11:00', end: '17:00' },
  6: { label: 'Saturday', start: '11:00', end: '17:00' },
};

export const seededBookings = [
  {
    id: 'BS-DEMO-1001',
    serviceId: 'ladys-haircut-long-hair',
    stylistId: 'elena',
    date: '',
    time: '12:00',
    client: { name: 'Demo client', phone: '+45 12 34 56 78', email: 'demo@blacksilva.ro' },
    protection: true,
    productId: 'repair-mask',
    status: 'confirmed',
    source: 'seed',
    createdAt: 'demo',
  },
];
