export const salon = {
  name: 'BlackSilva',
  email: 'blacksilvahd@gmail.com',
  address: 'Badstuestraede 16, 1053 Kobenhavn',
  mapsUrl:
    'https://www.google.com/maps/search/?api=1&query=Badstuestr%C3%A6de+16%2C+1053+K%C3%B8benhavn',
  hours: 'Wed 14-20 / Thu-Sun 11-17',
};

export const stylists = [
  {
    id: 'eduard',
    name: 'Eduard',
    role: 'Men grooming specialist',
    initial: 'E',
    focus: "Since 2018, I've helped over 800 clients walk out looking exactly how they want to be seen.",
    specialties: ['Men haircuts', 'Beard', 'Grooming'],
  },
  {
    id: 'elena',
    name: 'Elena',
    role: 'Women hair specialist',
    initial: 'E',
    focus: "Since 2018, I've helped over 800 clients walk out looking exactly how they want to be seen.",
    specialties: ['Women haircuts', 'Styling', 'Unisex'],
  },
  {
    id: 'chair',
    name: 'Chair 01',
    role: 'Rentable salon station',
    initial: 'C',
    focus: 'A ready salon station for independent barbers or stylists, with direct booking access.',
    specialties: ['Chair rental', 'Studio'],
  },
];

export const services = [
  {
    id: 'men-haircut',
    name: 'Precision haircut',
    category: 'Men',
    duration: 45,
    price: 180,
    staffIds: ['eduard', 'elena'],
    description: 'Walk out sharper before you say a word.',
    popular: true,
  },
  {
    id: 'haircut-beard',
    name: 'Full cut + beard combo',
    category: 'Men',
    duration: 60,
    price: 260,
    staffIds: ['eduard'],
    description: 'Leave with a face-framing look that feels intentional from every angle.',
    popular: true,
  },
  {
    id: 'kids-cut',
    name: 'Kids cut',
    category: 'Men',
    duration: 30,
    price: 150,
    staffIds: ['eduard', 'elena'],
    description: 'A calm, clean cut that makes them feel confident leaving the chair.',
    popular: true,
  },
  {
    id: 'beard-trim',
    name: 'Beard Trim',
    category: 'Men',
    duration: 25,
    price: 140,
    staffIds: ['eduard'],
    description: 'Look cleaner, more defined, and ready for close-up conversations.',
  },
  {
    id: 'women-haircut',
    name: "Women's Haircut",
    category: 'Women',
    duration: 60,
    price: 320,
    staffIds: ['elena'],
    description: 'Feel like your hair finally matches the version of you people notice first.',
    popular: true,
  },
  {
    id: 'wash-cut-style',
    name: 'Wash + Cut + Styling',
    category: 'Women',
    duration: 75,
    price: 420,
    staffIds: ['elena'],
    description: 'Walk out with movement, polish, and a look that carries the room.',
  },
  {
    id: 'blow-dry',
    name: 'Blow Dry / Styling',
    category: 'Styling',
    duration: 40,
    price: 240,
    staffIds: ['elena'],
    description: 'Step into the day with hair that already feels camera-ready.',
  },
  {
    id: 'unisex-refresh',
    name: 'Unisex Refresh',
    category: 'Unisex',
    duration: 50,
    price: 280,
    staffIds: ['eduard', 'elena'],
    description: 'Reset your look in one visit and feel put together again.',
  },
  {
    id: 'pack-five',
    name: '5x Haircut Pack',
    category: 'Packages',
    duration: 45,
    price: 799,
    staffIds: ['eduard'],
    description: 'Stay consistently sharp without thinking about your next appointment.',
  },
  {
    id: 'chair-rental-halfday',
    name: 'Chair Rental / Half Day',
    category: 'Business',
    duration: 240,
    price: 900,
    staffIds: ['chair'],
    description: 'Rent the BlackSilva chair for half a day, with admin confirmation.',
  },
  {
    id: 'chair-rental-day',
    name: 'Chair Rental / Full Day',
    category: 'Business',
    duration: 360,
    price: 1500,
    staffIds: ['chair'],
    description: 'Book a full salon station for one workday.',
  },
];

export const products = [
  { id: 'none', name: 'No product', price: 0, stock: 0, category: 'None' },
  { id: 'stylist-pick', name: 'Stylist pick', price: 180, stock: 12, category: 'Salon Pick' },
  { id: 'texture-spray', name: 'Texture Salt Spray', price: 195, stock: 18, category: 'Styling' },
  { id: 'matte-clay', name: 'Matte Clay', price: 210, stock: 9, category: 'Styling' },
  { id: 'repair-mask', name: 'Repair Mask No.7', price: 320, stock: 6, category: 'Care' },
];

export const openingHours = {
  0: { label: 'Sunday', start: '11:00', end: '17:00' },
  1: null,
  2: null,
  3: { label: 'Wednesday', start: '14:00', end: '20:00' },
  4: { label: 'Thursday', start: '11:00', end: '17:00' },
  5: { label: 'Friday', start: '11:00', end: '17:00' },
  6: { label: 'Saturday', start: '11:00', end: '17:00' },
};

export const seededBookings = [
  {
    id: 'BS-DEMO-1001',
    serviceId: 'women-haircut',
    stylistId: 'elena',
    date: '',
    time: '12:00',
    client: { name: 'Demo client', phone: '+45 12 34 56 78', email: 'demo@blacksilva.ro' },
    protection: true,
    productId: 'repair-mask',
    status: 'confirmed',
    source: 'seed',
    createdAt: 'demo',
  },
];
